### PR TITLE
fix #768: prevent error when starred bot is not on recently used list

### LINKED ISSUE #768: [BUG] Cannot make bot starred (or pinned) on certain circumstance
## 🚨 **Please Note** 🚨

To ensure efficient investigation of the issue, please fill out the fields below with as much detail as possible. **Reports that do not follow this template may be closed without notification.** We appreciate your cooperation.

## 🐞Describe the bug

When bot conversation screen (https://\<bedrock-claude-chat\>/bot/\<bot-id\>), pressing star button on top-right corner does not actually marks/unmarks the bot as starred/pinned.

## 🔄 To Reproduce

1. Create shared bot without knowledge.
   (it seems that shared bot without knowledge never shows up in "Recently Used", https://github.com/aws-samples/bedrock-claude-chat/blob/fd6239e751a3e6a1730332fee3058e13ec208fa8/backend/app/usecases/bot.py#L610)
2. Open bot conversation screen by shared URL, by non bot-owner
3. Press star button on top-right corner
4.
  - Expects star icon changes, but it's reverted in 2~3 sec
  - Expects API (`PATCH /bot/{id}/pinned`) is called, but it's not called
  - Error raised in browser console
    ```
    index-BwgD4CXd.js:336 Uncaught TypeError: Cannot set properties of undefined (setting 'isPinned')
    at index-BwgD4CXd.js:336:56181
    at produce (index-BwgD4CXd.js:331:12429)
    at updateSharedBotStarred (index-BwgD4CXd.js:336:56155)
    at Object.onClick (index-BwgD4CXd.js:670:4354)
    at onClick (index-BwgD4CXd.js:325:2821)
    at Object.TQ (index-BwgD4CXd.js:37:9864)
    at NQ (index-BwgD4CXd.js:37:10018)
    at RQ (index-BwgD4CXd.js:37:10075)
    at SN (index-BwgD4CXd.js:37:31512)
    at cz (index-BwgD4CXd.js:37:31929)
    ```

## 📷 Screenshots

None.

## 🔎 Logs for Chat Issues

None.

## 🔎 Logs for Bot Creation/Update Issues

None.

## 📝 Additional context

I think that this occurs when the bot is not in "Recently Used" list, see  https://github.com/aws-samples/bedrock-claude-chat/blob/fd6239e751a3e6a1730332fee3058e13ec208fa8/frontend/src/hooks/useBot.ts#L162C45-L163C1

### PR DESCRIPTION
**Pull request by suzuki-safie**
*Issue #, if available:*
#768 

*Description of changes:*
- fix #768: prevent error when starred bot is not on recently used list
- make bot without KB appears in recently used list

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by statefb** [comment]
@suzuki-safie Thank you for bug report and creating PR! As for `useBot.ts` LGTM, but can I ask you why added `HasKnowledge` attribute to `BotMeta` and why resolves the issue. We'd be appreciated if you could explain on the code ( If it's difficult, on this thread instead of the code). Thank you!

File: frontend/src/hooks/useBot.ts [hunk 1]
```diff
@@ -158,7 +158,7 @@ const useBot = (shouldAutoRefreshMyBots?: boolean) => {
       const idx = recentlyUsedBots?.findIndex((bot) => bot.id === botId) ?? -1;
       mutateRecentlyUsedBots(
         produce(recentlyUsedBots, (draft) => {
-          if (draft) {
+          if (draft && idx !== -1) {
```
Comment (suzuki-safie) [inline frontend/src/hooks/useBot.ts:161]: This fixes the bug where pinning a bot that is not in the 'recently used list' fails.

File: backend/app/usecases/bot.py [hunk 2]
```diff
@@ -607,7 +610,7 @@ def fetch_all_bots(
 
     bot_metas = []
     for bot in bots:
-        if not bot.has_bedrock_knowledge_base:
+        if bot.has_knowledge and not bot.has_bedrock_knowledge_base:
```
Comment (suzuki-safie) [inline backend/app/usecases/bot.py:613]: The original code seems to be trying to remove stale bots (1.x bots with pgvector) from the list, but it removes all bots without RAG. This change allows bots without RAG to appear in both the "recently used" list and "starred" list.

File: backend/app/repositories/models/custom_bot.py [hunk 3]
```diff
@@ -348,6 +348,7 @@ class BotMeta(BaseModel):
     # This can be `False` if the bot is not owned by the user and original bot is removed.
     available: bool
     sync_status: type_sync_status
+    has_knowledge: bool
```
Comment (suzuki-safie) [inline backend/app/repositories/models/custom_bot.py:351]: Used to distinguish pgvector bot (`has_knowledge && !has_bedrock_knowledge_base`), KB bot (`has_knowledge && has_bedrock_knowledge_base`) and bot without RAG (`!has_knowledge`).

**Comment by suzuki-safie** [comment]
@statefb
I have added some PR comments. Would you please review them and let me know if additional information or clarification is needed? Thank you for your consideration.

**Review by statefb — APPROVED** [review]
LGTM! Thank you for considering backward compatibility and your thoughtful commits!!
